### ISSUE TITLE
Apostrophes in Places

### ISSUE THREAD

**Issue by monopoisoner** [RolePlayGateway/roleplaygateway#10]
Using apostrophes (possibly any non basic alphanumeric character?) in Place Names creates an inaccessible URL that cannot be deleted or changed from the console.

**Comment by lostamongtrees** [comment]
This issue seems to have been resolved
Example:
https://www.roleplaygateway.com/roleplay/the-multiverse/places/steelies-diner
![image](https://user-images.githubusercontent.com/52435234/60765369-96960300-a067-11e9-826f-b3950aeff652.png)
