### ISSUE TITLE
Owner location subscribing

### ISSUE THREAD

**Issue by littlekreen** [RolePlayGateway/roleplaygateway#101]
Much like how characters have a subscribe button it would be nice for owners to have such a button appear as an opt-in for their own locations. basically touching the same feed as the character subscribe but without the query dependance on looking for a specific set of player characters.

**Comment by martindale** [comment]
Notifications for all posts in a location?

**Comment by littlekreen** [comment]
yes, I didn't even know there was a post in gehenna for me to reply to until months after the fact.

**Comment by lostamongtrees** [comment]
Location subscriptions in general would be ideal!

**Comment by lostamongtrees** [comment]
Thank you @littlekreen for everything always!  Closing this issue to compile it with like-kinds regarding subscribing! see #120

**Comment by lostamongtrees** [comment]
owners now receive notifications for posts posted in their location awesome job and thanks @littlekreen !
