### ISSUE TITLE
Bottom chat bar historical data causing site to be unusuable in mobiles

### ISSUE THREAD

**Issue by littlekreen** [RolePlayGateway/roleplaygateway#103]
It attempts to load all messages from every messages they've ever had. The result of this is enough to grind a mobile browser on many phones to a screeching halt. A reasonable epoch needs to be set of marking all messages as read since before the installation of the bottom chat. Thus only loading a small subset of messages.

**Comment by lostamongtrees** [comment]
I can load everything fine, can anyone else confirm?

**Comment by lostamongtrees** [comment]
Thanks littlekreen! This has been resolved
