### ISSUE TITLE
RPG Chat not working

### ISSUE THREAD

**Issue by LookingatPerks** [RolePlayGateway/roleplaygateway#104]
For some reason, even after clearing my cache, relogging in and out, refreshing the page, and restarting the whole browser, RPG chat is not working for me.

https://media.discordapp.net/attachments/330820217347506199/496410760478457866/2018-10-01_4.png?width=600&height=338

Image.  I posted it on Discord originally, its a screenshot of what happens when I try to enter anything into the chat.

**Comment by colearkenach** [comment]
Getting the same issue on my end, I've logged in and out with no progress.

**Comment by martindale** [comment]
We found that this is fairly consistently resolved upon clearing of _cookies_ for `roleplaygateway.com` — you will have to log in again, but the problem should go away.  Double and triple check that you've cleared cookies, then report back if the problem persists.

As always, tracking down a reproducible condition makes finding bugs a lot easier.  If anyone can find information on what _causes_ this, we can narrow down where to find it!

**Comment by colearkenach** [comment]
@martindale Later in the day after the issue occurred it seemed to have fixed itself. I tried logging in today and it happened again, so I cleared my cookies just a few moments ago and the problem still persists.

I'm going to wait and try to chat in a bit.

**Comment by martindale** [comment]
@LookingatPerks can you try chat.roleplaygateway.com and tell me if if it's any better?

**Comment by lostamongtrees** [comment]
Closing this issue as we progress
