### ISSUE TITLE
RPG Chat Issue

### ISSUE THREAD

**Issue by ersatz-creed** [RolePlayGateway/roleplaygateway#105]
I Log In, I go to the chat, and I go to talk only to have the chat Game Master reply: 

"You cannot participate because you are not logged in as a registered user. You should register or log in."

I can access all other places and parts of the site save for the Chat which seems convinced I am not logged in despite being logged in

**Comment by martindale** [comment]
This is for the shoutbox, I'm guessing, not chat.roleplaygateway.com?  If so, clear your cache, try again, and if it still doesn't work, clear your cookies and re-log.
