### ISSUE TITLE
Scrollybar in Characters Tagged

### ISSUE THREAD

**Issue by lostamongtrees** [RolePlayGateway/roleplaygateway#140]
![image](https://user-images.githubusercontent.com/52435234/62841037-4ebf5880-bc71-11e9-8070-4ee4edefa1f8.png)

**Comment by lostamongtrees** [comment]
If it functioned proper I see the use but alas! lol

![image](https://user-images.githubusercontent.com/52435234/62841060-afe72c00-bc71-11e9-8874-f871fb5fb023.png)

**Comment by lostamongtrees** [comment]
![image](https://user-images.githubusercontent.com/52435234/63992155-99860080-cab8-11e9-8c3b-9eb420be82ef.png)
seems to be fixed
![image](https://user-images.githubusercontent.com/52435234/63992217-db16ab80-cab8-11e9-95b8-9f648e7df91e.png)

scrollybar now adjusts to height !
thank you!!!

**Comment by martindale** [comment]
This still isn't quite right.  Need to take another look.

**Comment by lostamongtrees** [comment]
When there are "too many" characters, the icons stop loading & are just rawlinks of the names with broken images behind

**Comment by lostamongtrees** [comment]
Going to close this issue since the scrollybar is there and does function
