### ISSUE TITLE
Forest Glen leads to OOC chat

### ISSUE THREAD

**Issue by lostamongtrees** [RolePlayGateway/roleplaygateway#141]
https://www.roleplaygateway.com/universes/the-multiverse/places/out-of-character-ooc
![image](https://user-images.githubusercontent.com/52435234/63201781-b4865880-c054-11e9-9178-014e39e4a6a0.png)

**Comment by martindale** [comment]
This is [now fixed](https://www.roleplaygateway.com/universes/the-multiverse/places/forest-glen)!
