### ISSUE TITLE
Block Of Characters

### ISSUE THREAD

**Issue by lostamongtrees** [RolePlayGateway/roleplaygateway#154]
https://www.roleplaygateway.com/characters-recent-the-last-post-issue-t111719.html

>There is a massive issue that isn't the end of the world, but it is quite annoying. When replying to a roleplay, we are normally allowed to see our post as we type it out. For those of us who are more aesthetically inclined, we love this feature. However, for the last week or so, this monstrous list of names stands between our text box and the preview. It's a pain in the butt. It is not exclusive to one Roleplay, either, because when I go from Camp Athens to another RP, I get the same thing.

user:  Dreamwaker

![image](https://user-images.githubusercontent.com/52435234/63992010-e74e3900-cab7-11e9-8097-0b298ed7f6b5.png)

**Comment by martindale** [comment]
Yikes!  This one is ugly, I'll try to get a fix in this weekend.

**Comment by lostamongtrees** [comment]
![image](https://user-images.githubusercontent.com/52435234/68357805-86109a80-00e4-11ea-9b29-4ce48c2899c9.png)

much better!
