### ISSUE TITLE
Snippets have the wrong character portrait.

### ISSUE THREAD

**Issue by LawOfTheLand** [RolePlayGateway/roleplaygateway#176]
https://www.roleplaygateway.com/snippets/2776495 It's supposed to be Cryoface saying it, but instead it's one of the other tagged characters.

**Comment by lostamongtrees** [comment]
seems to target last character tagged for portrait

**Comment by lostamongtrees** [comment]
- arcs page is accurate
- place page is accurate
- character page is accurate

problem alienated to snippets

**Comment by lostamongtrees** [comment]
all fixed!
![image](https://user-images.githubusercontent.com/52435234/68092331-04a4d800-fe58-11e9-8a89-f78731006fdb.png)
thanks again law <3
