### ISSUE TITLE
author medal 502

### ISSUE THREAD

**Issue by lostamongtrees** [RolePlayGateway/roleplaygateway#178]
![image](https://user-images.githubusercontent.com/52435234/65647184-e2ec4180-dfcb-11e9-8f38-1785643e924a.png)

**Comment by lostamongtrees** [comment]
![image](https://user-images.githubusercontent.com/52435234/65647197-f0093080-dfcb-11e9-9e99-65b8d48333d3.png)

**Comment by martindale** [comment]
Ops issue.  Not a bug.
