### ISSUE TITLE
community 502

### ISSUE THREAD

**Issue by lostamongtrees** [RolePlayGateway/roleplaygateway#179]
![image](https://user-images.githubusercontent.com/52435234/65647349-6c037880-dfcc-11e9-9fff-18d1fc3e742e.png)

![image](https://user-images.githubusercontent.com/52435234/65647352-702f9600-dfcc-11e9-8b1a-feaf8a4a8c13.png)

**Comment by martindale** [comment]
Ops issue.  Not a bug.
