### ISSUE TITLE
Clicking "Select All" will send you to the home page.

### ISSUE THREAD

**Issue by bumbahlee** [RolePlayGateway/roleplaygateway#19]
![select all](https://cloud.githubusercontent.com/assets/28374618/25687344/41e769a0-303b-11e7-9a2c-dc27b132816d.jpg)
![front](https://cloud.githubusercontent.com/assets/28374618/25687350/4f9e34a2-303b-11e7-85e5-a5602e7ba1e9.jpg)

When I went to "Select All" in a RP Forum it sent me to the home page.

**Comment by lostamongtrees** [comment]
![image](https://user-images.githubusercontent.com/52435234/60765197-60a34f80-a064-11e9-8249-485204ad9a24.png)

closing-resolved! Thank you again @bumbahlee
