### ISSUE TITLE
Messages stalling, not going through, piling up, repeating

### ISSUE THREAD

**Issue by shentino** [RolePlayGateway/roleplaygateway#196]
Quite often lately when I go to https://www.roleplaygateway.com/explorer/?characterID=262384&roleplayID=1 my posts either get stuck for a few minutes, sometimes don't go through at all, and sometimes pile up on the server without refreshing on my end until a manual F5 spills out a bunch of duplicates

Also for some reason I get bogus notifications for my *own* posts in my rp, when this didn't happen before.  I've had 10 notices piled up for the same message that had wound up getting repeated by mistake

**Comment by lostamongtrees** [comment]
#160

**Comment by lostamongtrees** [comment]
I've noticed that the ticker in the bottom left corner freezes completely when you submit a post sometimes - which indicates that the post went through and it's time for the page to refresh, but the post isn't showing up

**Comment by shentino** [comment]
https://www.roleplaygateway.com/notifications is also giving me notifications for my own posts, as in, the number goes up after I make...so it's like I'm notifying myself which is rather spurious as I already know damn well when I'm making a post

**Comment by shentino** [comment]
Replication instructions:  Reply to an RP you're posting in.  It will send you a notice for your own post instead of just limiting itself to notices for other people posting in your RP.

Also often the interface at https://www.roleplaygateway.com/explorer/?characterID=262384&roleplayID=1 doesn't autorefresh after a post is made

**Comment by shentino** [comment]
Interesting, I just noticed something

Seems that when I use /ooc, it echos right away, but when I post ICly, it doesn't reflect back

Refreshing with F5 shows it though

**Comment by lostamongtrees** [comment]
closing to merge with #160 thanks again for all your help @shentino !
