### ISSUE TITLE
all present characters auto-taggable from place page regardless of tags in prior post

### ISSUE THREAD

**Issue by lostamongtrees** [RolePlayGateway/roleplaygateway#198]
![image](https://user-images.githubusercontent.com/52435234/70874667-21691b00-1f81-11ea-8a37-9e5a2d79d624.png)

> Okay. I don't get this. The last post in Castelia is yours, and yet everyone physically located there is tagged for me. The only way I was able to force out a post last time was with Tag All. 

LawOfTheLand and Ritnio are working on this one as well, attempting to hone in further

**Comment by martindale** [comment]
This is not a bug; all characters present are available for rapid-tagging, with the added bonus of including characters _which were tagged in the most recent post_.  The header description is incorrect and should be changed.

**Comment by Lady-Awinita** [comment]
Even when those characters arent in the scene at hand ? Just physically in the place characters BAM can tag if you want, so when you post without tagging them they STILL show up as tagable ? This feels like it shouldnt happen, but it might just be me

**Comment by martindale** [comment]
> Even when those characters arent in the scene at hand ? Just physically in the place characters BAM can tag if you want, so when you post without tagging them they STILL show up as tagable ? This feels like it shouldnt happen, but it might just be me

Yes, if other players' characters are present, you should not be ignoring them when publishing new content to the location.  They must be given the opportunity to respond, so sending them a notification is not only polite, but usually required by a Universe's rules.
