### ISSUE TITLE
Sync with Feedback Forum

### ISSUE THREAD

**Issue by martindale** [RolePlayGateway/roleplaygateway#2]
We need to comb through the [feedback forum](https://rpg.uservoice.com) and document action items that are outstanding.  Ideally, this process will result in all open ideas and suggestions in the feedback forum having an attached status, which means we'll need to make some final decisions on implementation details of unrealized features.

Anything with a clear "go" should be created as an issue here on GitHub, and the status of the idea on the forum updated to link to the new location.

**Comment by lostamongtrees** [comment]
Complete!
