### ISSUE TITLE
Clicking the timestamp on a post will take you to a different place in the roleplay.

### ISSUE THREAD

**Issue by LawOfTheLand** [RolePlayGateway/roleplaygateway#20]
Specifically, I'm going through some of my character's old Multiverse posts, tagging all the things I remember, and notice that some of my old Gambit's Bar posts redirect to Castelia City. The post id number remains intact, so it's likely that you'll be taken to an empty activity page.

**Comment by martindale** [comment]
Hrm.  Can we gather more information on this one?  Why Castelia City of all places?

**Comment by LawOfTheLand** [comment]
No freaking clue. At first I thought that this was fixed to the location with the most recent post (and this bug was duplicated in another RP by Marin) but it's still going to Castelia even though the most recent post is currently in Lumiose City.

**Comment by lostamongtrees** [comment]
Closing this issue, see #98 - thank you @LawOfTheLand !
