### ISSUE TITLE
Cannot update avatars

### ISSUE THREAD

**Issue by Lady-Awinita** [RolePlayGateway/roleplaygateway#205]
When attempting to fix a broken avatar in the top bar next to my name, I first get logged out. Then once lofgged back in I was able to DELETE the avatar. So I can try to fix it

I go to try and fix and instead of loading the "You have updated your profile" page the site times out to "The site cannot be reached"

EDIT 1: Avatars in top bar next top username is a empty image placeholder/broken image link placeholder, the popup on hovering over a username with a gif avatar is also broken showing the same broken image outline

EDIT 2: I can now see my avatar {top bar} but not inthe popup. This has happened before so I think I'll drop this issue now. consider it fixed

**Comment by martindale** [comment]
Let's make sure this gets tested with a full registration of a new user, ideally on multiple browsers...

**Comment by lostamongtrees** [comment]
@Lady-Awinita is the avatar updated across the board? Can you create a side account and test the avatar-setting process, see if you get logged out - also what browser are you using?

**Comment by lostamongtrees** [comment]
Checking in to see if anyone was able to replicate, as I have not been able to

**Comment by lostamongtrees** [comment]
closing this issue as it seems to have been resolved
