### ISSUE TITLE
SUGGESTION: Post Order preferences for character histories

### ISSUE THREAD

**Issue by Lady-Awinita** [RolePlayGateway/roleplaygateway#206]
Ok this is more of a suggestion than a issue; but I have ont he forums the ability ot pick how I want the forum threads to read. For example the forums have a seting to post new posts at either the bottom or the top of each thread, AKA "newest post first"

Can this also be done for character post histories ? A setting in the user settings to set how they ewant character histories to read ? Something like

"Newest post at the bottom of the last page"
or
"Newest Post at the Top of the first page"

Can this be done ?

**Comment by lostamongtrees** [comment]
#14 going to close & merge

**Comment by Lady-Awinita** [comment]
Actually this has nothing to do with issue #14 Because this is focused on CHARACTER HISTORY not RP history directly. What I would like is to have my most recent post listed in my character history instead of the oldest post at the top

**Comment by lostamongtrees** [comment]
It all has to do with pagination.
