### ISSUE TITLE
Introduction Thread Links from Introductions Room on RPG Chat Lead to Whitescreen

### ISSUE THREAD

**Issue by lostamongtrees** [RolePlayGateway/roleplaygateway#227]
clicking these links
![image](https://user-images.githubusercontent.com/52435234/73388381-1dc6f480-42a0-11ea-8cbd-840ca6f845e9.png)

lead to
![image](https://user-images.githubusercontent.com/52435234/73388353-10aa0580-42a0-11ea-9ccc-2ce13586a926.png)

https://www.roleplaygateway.com/topic-t112259.html

**Comment by martindale** [comment]
Most likely a banned user.  Check the username, which should also be linked in the same message.  Delete (or have a moderator delete) messages for nuked accounts, close this if confirmed.

**Comment by lostamongtrees** [comment]
seems to be fixed closing issue thank you great work
