### ISSUE TITLE
"Tag All" button erroneously includes "Raven Summers"

### ISSUE THREAD

**Issue by colearkenach** [RolePlayGateway/roleplaygateway#24]
https://www.roleplaygateway.com/roleplay/the-multiverse/characters/raven-summers?start=20

Raven Summers is (or at least, was) able to be used in locations that aren't the Multiverse and as such has many broken links in non-MV locations.

**Comment by lostamongtrees** [comment]
This has been resolved! Thank you @Jhar226 !
