### ISSUE TITLE
Persistent Error when logging into RPG Chat

### ISSUE THREAD

**Issue by ChaoticMarin** [RolePlayGateway/roleplaygateway#243]
Laptop's broken again. I tried logging into https://chat.roleplaygateway.com/ on my desktop, but it gives me this error immediately upon logging in every time I try.

![image](https://user-images.githubusercontent.com/6273506/74094022-81bf9900-4aa8-11ea-990b-2c65feaf3441.png)

**Comment by martindale** [comment]
Use all-lowercase Fabric address for login — we need to improve the onboarding flow before this is ready to go public...

**Comment by ChaoticMarin** [comment]
Thank you~! That solved my problem.
