### ISSUE TITLE
Fatal error on site login.

### ISSUE THREAD

**Issue by LawOfTheLand** [RolePlayGateway/roleplaygateway#25]
On login, instead of being taken to the landing page, this exception is thrown:

Fatal error: Call to undefined function award_medal_from() in /var/www/html/includes/functions.php on line 4159

**Comment by martindale** [comment]
This error should go away as of a few minutes ago.  Can you confirm?

**Comment by LawOfTheLand** [comment]
New error now that I did the form resubmission.

General Error
SQL ERROR [ mysqli ]

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '1 )' at line 5 [1064]

An SQL error occurred while fetching this page. Please contact the Board Administrator if this problem persists.

**Comment by lostamongtrees** [comment]
Can't replicate error, closing issue
Thanks @LawOfTheLand !
