### ISSUE TITLE
Log outs are getting bad, like REALLY bad!

### ISSUE THREAD

**Issue by Ritnio** [RolePlayGateway/roleplaygateway#262]
I've been dodging reporting here because of a conception that the backlash would produce negative images on anything I have to say, critic or not. But it's gotten to the point that I'm tossing that out the window. 

My GOD are the log outs getting horrid. I can barely stay logged in to switch to my own notifications, let alone go to another page from there! I have to like keep re-logging in and doing the whole journey again and pray to the overlord of pancakes or something that it works. Even then, his power is limited.

Ok, this isn't meant to be a joke but I keep going there, sorry. I'm being completely serious in that this issue is becoming a bigger issue. It's like a small epidemic exploding into a pandemic but like, not as severe as death. Well, I mean except to my neighbours when I get angry after the 12th time trying to go two pages into the site. 

I'm no tech wiz, I can't come on here and go "It's the thingymihitsit in the code for the googly pineapples with the Hooglme" or whatever the heck you tech head's say. I just know with my minimal knowledge that whatever is going on, it hates the like "signal" or whatever that tells a site you're logged in and keeps refreshing it. 

Or something like that. I dunno. It might just like sipping a Martini more, who knows? I just know it's getting annoying. Please do like... maybe something about it? Even enough where I can go 3 pages deep. That would be monumental! 

Thanks for reading this... whatever the hell complaint this ended up being.

- Ritnio

**Comment by lostamongtrees** [comment]
Your feedback is so important, thank you! Coders have been working very hard to fix this bug— i do have a couple questions to see if we can narrow some more things down:

- are you accessing through mobile or a pc
- if mobile, what phone & browser
- if pc, what browser & extensions

Your frustration is completely understandable. Thank you for helping us get to the bottom of this plague!

**Comment by Ritnio** [comment]
Pc. Chrome. No extensions.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by martindale** [comment]
Duplicate of #192 — we're keeping track of everything there!
