### ISSUE TITLE
Traveling from Notifications to Private Messeges results in broken page

### ISSUE THREAD

**Issue by Lady-Awinita** [RolePlayGateway/roleplaygateway#267]
Basically I was sent a PM recently, and it showed up in the notifcations as normal, HOWEVER clicking the link "{NAME} has sent you a new message" only leads to a blank white page {No I did not get logged out during the movement}

HOWEVER the drop down menu to private messages works as normal

**Comment by martindale** [comment]
Fairly certain this is resolved; links in PM notifications seem to work.  Please re-open if it occurs again!
