### ISSUE TITLE
rooms menu frustrating

### ISSUE THREAD

**Issue by lostamongtrees** [RolePlayGateway/roleplaygateway#268]
On the RPG Chat app, the rooms list side bar is frustrating in design.

![image](https://user-images.githubusercontent.com/52435234/76888271-0648c880-685a-11ea-9c8c-0eac8ceb68d9.png)

There's no rhyme or reason, seemingly, to how to make each or either column bigger or smaller without straight fiddling with it until you get the desired results. Missing messages etc as a result.

**Comment by martindale** [comment]
This should be fixed in recent versions and on [the web chat](https://chat.roleplaygateway.com)!
