### ISSUE TITLE
Clicking "Submit a Character" shows glitched characters

### ISSUE THREAD

**Issue by colearkenach** [RolePlayGateway/roleplaygateway#29]
On "The Multiverse" if you click "Submit a Character" it'll show characters from the orphanage under the "Available Characters" line, however all of the characters listed lead to 404 links due to not specifying the universe within the link (example: clicking on Click Avernus leads to the following link: https://www.roleplaygateway.com/roleplay//characters/click-avernus/ )

Edit: This can be replicated in other roleplays, not just The Multiverse.

**Comment by martindale** [comment]
Patched this up, should be a random selection of 3 available characters with correctly working links now. :)
