### ISSUE TITLE
"Select All Coding"

### ISSUE THREAD

**Issue by oleande-r** [RolePlayGateway/roleplaygateway#30]
Whenever using the 'code' brackets to show actual code, if you click "Select All" it'll either send you to the front page of the site or it'll add a # symbol to the url. Specifically, it'll send you to the front page if the 'code' brackets were located in a forum post but if it was located in a character profile it'll only add the # symbol. [Here is an image to specify what I'm talking about.](https://i.imgur.com/rq02I5O.png)

**Comment by martindale** [comment]
Thank you so much for reporting this!  I'll be taking this on shortly.

**Comment by lostamongtrees** [comment]
![image](https://user-images.githubusercontent.com/52435234/60765177-1d48e100-a064-11e9-924b-4f979d9d1921.png)

Closing as this has been resolved! Thanks again @oleande-r !
