### ISSUE TITLE
tumblr autopost api broken- rpg tumblr seemingly gone as well

### ISSUE THREAD

**Issue by thaumatology** [RolePlayGateway/roleplaygateway#313]
<img width="1158" alt="Screen Shot 2023-01-04 at 4 40 56 PM" src="https://user-images.githubusercontent.com/31420084/210645984-12294de0-ab99-4fc3-ae8b-5ddd2dae6c43.png">

tried to submit a post from the page in decrepit graveyard

went back to post again, same code

**Comment by thaumatology** [comment]
shell seems to work seamlessly, also tried to use forge and it borked everytrhing might be first post post forge is borked

**Comment by thaumatology** [comment]
ok it did post, both times

**Comment by thaumatology** [comment]
tumblr autopost api broken- rpg tumblr seemingly gone as well
likely got banned

**Comment by martindale** [comment]
Closed as fixed
