### ISSUE TITLE
link to image resizer broken in character page

### ISSUE THREAD

**Issue by thaumatology** [RolePlayGateway/roleplaygateway#314]
leads to nowhere, replace or add auto-resizer

**Comment by martindale** [comment]
Supply another and will replace

**Comment by thaumatology** [comment]
https://www.resizepixel.com/

this one doesn't ask for sign up, seems to retain the best quality

**Comment by thaumatology** [comment]
increased influx of active players to site, 
seems to be partially sourced from sigurd,
partially from legacy comm
seeking update to this asap

**Comment by martindale** [comment]
Fixed on:
- New Character upload
- Existing Character modify

**Comment by thaumatology** [comment]
did this fix accidentally the site? it's down
