### ISSUE TITLE
/christen override with /placeName

### ISSUE THREAD

**Issue by thaumatology** [RolePlayGateway/roleplaygateway#323]
<img width="1395" alt="Screen Shot 2023-01-12 at 4 19 25 PM" src="https://user-images.githubusercontent.com/31420084/212172067-c4c65066-1839-4e2a-856b-ea661097bdcb.png">

unsure if this only worked because I am also a GM in the universe, but this is a thing

**Comment by martindale** [comment]
This is intended behavior — `/placeName` overrides the `/christen` behavior and sets the place URL to a publicly predictable one

**Comment by thaumatology** [comment]
cool cool good to know
