### ISSUE TITLE
Tagging character in old posts

### ISSUE THREAD

**Issue by DemiKara** [RolePlayGateway/roleplaygateway#33]
When other users tag a character in an older post, it generates a notification. Notification does not direct to correct post, instead goes to activity past. See Discord for details.

**Comment by martindale** [comment]
Can you publish the details here for the folks not in Discord?

**Comment by DemiKara** [comment]
I've been working on this today. Results are the same for logged in users and nonlogged in users. This has not been tested for logged in users who do not 'own' the tagged character. Attached are the relevant files.

about Character Name takes user to the activity page of the relevant roleplay, rather than to the tagged post in question, as it does with new posts. All other links work.


![brokethething](https://user-images.githubusercontent.com/15753498/26895932-c80cfee2-4b88-11e7-91f1-6bf143ab9708.PNG)
![anonymous user](https://user-images.githubusercontent.com/15753498/26895937-cc8ce9c8-4b88-11e7-9869-0a880cba0f3d.PNG)

**Comment by lostamongtrees** [comment]
Thanks again @DemiKara - this has been resolved, can confirm directs to snippet
![image](https://user-images.githubusercontent.com/52435234/60765031-a90d3e00-a061-11e9-8aef-4802e79bee26.png)
leads to
https://www.roleplaygateway.com/snippets/2777488

`/me sings closing time`
