### ISSUE TITLE
Edit brings up Syntax Error when editing a place in the Multiverse

### ISSUE THREAD

**Issue by colearkenach** [RolePlayGateway/roleplaygateway#34]
When submitting an edit to a places page, I received "Parse error: syntax error, unexpected T_EXIT, expecting T_FUNCTION in /var/www/html/includes/ucp/ucp_roleplays.php on line 2203"

This isn't brought up when trying to edit characters, only places that I've seen so far.

**Comment by lostamongtrees** [comment]
Is it possible you were using a character not recognized by the site, as discussed in #58 ?
Cannot replicate error , closing issue until otherwise noted - thanks again @Jhar226 !
