### ISSUE TITLE
Vehicle creation commands not working

### ISSUE THREAD

**Issue by thaumatology** [RolePlayGateway/roleplaygateway#343]
<img width="682" alt="Screen Shot 2023-08-22 at 10 13 29 AM" src="https://github.com/RolePlayGateway/roleplaygateway/assets/31420084/961c4625-99a5-40f6-a96a-300757269f9d">

/hail New Vehicle Name did not work
/summon does not exist (Idk why i remember this command it likely never existed)
/hail (on it's own) produced the third result

unsure next steps

**Comment by martindale** [comment]
worked for me:

`/hail <Vehicle Type>` (select from [the Vehicles page](https://www.roleplaygateway.com/vehicles))
`/christen <Your Name>` to name the vessel
`/exit` to leave, `/warp <Destination Name>` to warp, etc.

**Comment by thaumatology** [comment]
ok - 
<img width="681" alt="Screen Shot 2023-08-26 at 10 24 01 AM" src="https://github.com/RolePlayGateway/roleplaygateway/assets/31420084/636127b1-55c6-42d3-ae14-1c7b188c5549">

we might want to edit this to say /hail <vehicle class> instead of Name, and link the list of vehicles in the /help section of chat
