### ISSUE TITLE
Fabric/Matrix chat completely offline

### ISSUE THREAD

**Issue by Lady-Awinita** [RolePlayGateway/roleplaygateway#352]
When attempting to connect to the new chat, the notice comes up as following

"ERR_CONNECTION_REFUSED"

I have tried several different devices. nothing is working and I am not the only one getting this issue

**Comment by thaumatology** [comment]
can confirm

**Comment by martindale** [comment]
you can use https://grove.chat in the interim, it will have access to all the same rooms

**Comment by Lady-Awinita** [comment]
Alright i had to make a new account for it, but it doesnt have any access to any of the RPG rooms; its like the RPG community server is entirely gone. Its confusing I guess ?

**Comment by martindale** [comment]
> Alright i had to make a new account for it, but it doesnt have any access to any of the RPG rooms; its like the RPG community server is entirely gone. Its confusing I guess ?

If you don't already have the rooms on the account someone from the RPG side will have to invite you

**Comment by Lady-Awinita** [comment]
I had to make an entirely new account though because Grove didnt recognise any of my passwords

**Comment by martindale** [comment]
chat.roleplaygateway.com seems online now...
grove.chat remains stable.

@Lady-Awinita `grove.chat` is a separate network from RPG, but it is the most important one.   You should have a browser tab open for both (if you don't use the clients).   Grove is focused on the wider market, whereas RPG is focused on the role-playing community.

Hope this helps!
