### ISSUE TITLE
Site down chat up

### ISSUE THREAD

**Issue by Lady-Awinita** [RolePlayGateway/roleplaygateway#355]
I was recommended to post this here on github instead of on twitter via lostamongtrees

Somehow it is the oppisite of what it was a week ago, suddenly the site is offline and the chat is working.

**Comment by thaumatology** [comment]
site still down chat still up

**Comment by Lady-Awinita** [comment]
We can now mark this as closed as the site has come back up thanks to Rem's hard work to get us out of this mess. But we can help Rem now by further reporting spambots
