### ISSUE TITLE
Character posts not showing on profil

### ISSUE THREAD

**Issue by DemiKara** [RolePlayGateway/roleplaygateway#37]
Character posts are not showing on their profile. See screenshots. I have noticed this across characters
Claire's profile displays this post, which should be the last post in the profile for The Abducted Ones
![from claires profile](https://user-images.githubusercontent.com/15753498/26947862-da2f1052-4c59-11e7-9849-ac900ffe5e3f.png)

The Abducted Ones profile displays this post as the final post.
![from abones profile](https://user-images.githubusercontent.com/15753498/26947861-da2e7390-4c59-11e7-8b8c-a0e5ce2eac38.png)

Periodically a post will also be missing from the Places tab, but will be visible on the character's profile, or on another character in the scenes profile. Are these related?

**Comment by martindale** [comment]
So some characters, but not all, seem to "drop" some of the posts they are correctly tagged in?  Can you tell if there's any pattern to this?

**Comment by DemiKara** [comment]
Let's see. The majority of dropped posts were made before switching to the tab system. 

However, that dropped post was made after. 

The characters were all made before. I can't really see a pattern, truth told. Most recent posts tag fine. This is the only one I've seen that hasn't. I'm sure there are others, but I haven't seen them yet.

**Comment by lostamongtrees** [comment]
Cannot seem to replicate issue, but awesome work @DemiKara . Closing - if issue re-presents itself, let us know! Thanks again!
