### ISSUE TITLE
Improved Creator Controls

### ISSUE THREAD

**Issue by martindale** [RolePlayGateway/roleplaygateway#4]
It'd be nice if users had complete autonomy to manage their own roleplay, including [the ability to close your own roleplay](http://rpg.uservoice.com/forums/22249-ideas-suggestions/suggestions/3465731-allow-a-user-to-close-their-own-roleplay).  Let's use this issue to aggregate a wishlist of desired features.

- [ ] ability to close own roleplay
- [ ] manage posts in roleplay (move, edit, delete)

**Comment by LawOfTheLand** [comment]
DemiKara suggests: Deleting posts (in case of double posting or site rule violation: RP rule violations can merely be retconned out) and moving posts to a different location. Say, someone posts in AP-755 when they're clearly in more of an elven forest glade.

**Comment by monopoisoner** [comment]
Would also like to include [this](https://rpg.uservoice.com/forums/22249-ideas-suggestions/suggestions/13473186-mark-rps-as-accepting-not-accepting) as an additional control for them.

**Comment by monopoisoner** [comment]
How about locking a "Place", similar to how we can lock certain threads in forums? It's a good compromise between deleting an unwanted Place and keeping it visible.

**Comment by lostamongtrees** [comment]
Closing this issue as these features have been implemented.
Thank you @monopoisoner & @LawOfTheLand & @DemiKara !
