### ISSUE TITLE
Notification link error

### ISSUE THREAD

**Issue by DemiKara** [RolePlayGateway/roleplaygateway#40]
When on notification page, a link to a pm from the notification of that pm does not find the pm. Exact message:

Information

Private message could not be found.

**Comment by martindale** [comment]
This is related to "folders", a massively-underutilized function that should perhaps be removed.  How many of our users even use folders (opportunity for a community-suggested query here! :D)?  If it's a low amount, perhaps we should just get rid of them entirely and always refer to PMs by ID.

**Comment by DemiKara** [comment]
We have folders?

**Comment by lostamongtrees** [comment]
Folders sounds like a tool more useful to archive IC content instead of making a storage RP? but yeah its a little confusing 
Also this may relate to the red dot issue

**Comment by lostamongtrees** [comment]
Appears to be fixed, thanks @DemiKara and @monopoisoner ! #8
