### ISSUE TITLE
Whispers in Chat not working

### ISSUE THREAD

**Issue by DemiKara** [RolePlayGateway/roleplaygateway#42]
Whispers in chat do not send.

Typing /msg DemiKara does not even generate an entry in chat, not even that of a failed command. This occurs whether users are in the same RP or not.

there is no delay in messages sent after the whisper appearing. Whispering appears completely disabled, including a you screwed up message.

First noticed 6/10/2017 midaftenoonish?

**Comment by lostamongtrees** [comment]
Closing this issue as it has been resolved. Thank you @DemiKara !
