### ISSUE TITLE
Default chat font has terrible kerning.

### ISSUE THREAD

**Issue by LawOfTheLand** [RolePlayGateway/roleplaygateway#43]
For our dyslexic and older users, words like "pom" and "porn" are fairly difficult to distinguish from one another unless one uses [code] tags, and [font] tags just straight don't work in the chat.

**Comment by martindale** [comment]
We recently acquired some assets for this.  Anyone recall where they went?

**Comment by colearkenach** [comment]
https://www.dyslexiefont.com/en/dyslexie-font/
https://www.roleplaygateway.com/fonts/dyslexie_bold_italic_es.ttf

**Comment by lostamongtrees** [comment]
closing this issue as oldchat is gone
