### ISSUE TITLE
"Places" button from chat has issues.

### ISSUE THREAD

**Issue by LawOfTheLand** [RolePlayGateway/roleplaygateway#46]
Places in "The Multiverse" (click) not only fails to load place images (I checked this with Castelia City) but when clicking on the View All Posts button for a place, it does nothing. (Also, the Launch Nuclear Warheads button still pops up a "Hey! Don't touch that!" but one wonders why else it might be put there.)

**Comment by martindale** [comment]
I'd like to do a ground-up redesign of the ideal chat interface at some point.

**Comment by lostamongtrees** [comment]
Closing this issue as we've far progressed beyond this point-thanks as always @LawOfTheLand !
