### ISSUE TITLE
Character names with hashtags breaks the in-chat list of characters.

### ISSUE THREAD

**Issue by LawOfTheLand** [RolePlayGateway/roleplaygateway#47]
Character name "Renegade #581" gets parsed such that it breaks ALL THE TAGS, thus laying all the bbcoding bare. Last seen in location Wing City Town Square in The Multiverse.

**Comment by lostamongtrees** [comment]
@LawOfTheLand at it again- thank you! Closing this issue as it has been resolved as we move forward with the new chat
