### ISSUE TITLE
The look command while OOC spits out a partial list of places in that roleplay.

### ISSUE THREAD

**Issue by LawOfTheLand** [RolePlayGateway/roleplaygateway#49]
I tried it with The Multiverse and got the following:

You have arrived at Out Of Character (OOC). Owner: RolePlayGateway

There are no visible exits!
There is no one else here.
Also: Mjötviðr; The Realms, Wynwood Keep, Ingham, Erheath, 83f3d533b35403a95b1b5741b2002232​, f26afa666a8ccda8f209e8bd31d3cb96​, ebcc4191bb228747a7c2214bd8571e5a​, e9f06373d03191113354eae5cacdfc60​, 892e54511a04bddd12eafe2937011737​, 9a7436f18d9d35aed41132b5772f2d22​, edd8530644c3ef9fbc7f41542bc6f35f​, 6be38bef62bc47b14e3ff95efba3440d​, Ymir's Heavenly Stairs

**Comment by lostamongtrees** [comment]
Thanks @LawOfTheLand  - closing this issue as we move forward
