### ISSUE TITLE
Teleportation isn't working for Mods

### ISSUE THREAD

**Issue by bumbahlee** [RolePlayGateway/roleplaygateway#50]
Well I don't know for the other mods, but I know for me it isn't working. Someone had called for a Mod in chat and it said to use /teleport 0 to get to them and I tried, but it gave me:

Game Master (GM)
Error: Unknown command: /teleport

Honestly I don't know if it is me or not, but Law said to put it here.

**Comment by martindale** [comment]
Can you please check to see if this is still occurring?

**Comment by lostamongtrees** [comment]
Thanks @bumbahlee as always! closing this issue
