### ISSUE TITLE
New Account Creation Bug

### ISSUE THREAD

**Issue by DemiKara** [RolePlayGateway/roleplaygateway#52]
> Russian_Death says:
> I just typed in my email, pressed the button, it said i got it wrong, I retyped it. then pressed the create button, and it didn't work. When I tryed to leave it loaded up this sites.... main thing..or whatever

Used 'bing' from windows 10

> WinterRose says:
> for me it didn't even load anything... it just said my username and email was already used after my second time trying then I went back and tried logging in again and it worked
> 

used safari from 'phone' (probably iOS)

Steps to replicate:
I accessed create a new account page in internet explorer on Windows 7.
Filled out form and clicked create new account. (as BetaTestBetsey)
Button showed click occurred, but no response from coding, did not move forward.
Navigated to log in, new log in did not work. E-mail to new user did not work.

I accessed create a new account page in mozilla firefox.
Filled out form and clicked create a new account (BetaTestBetsey)
Tab indicated that it was connecting for long period while indicating that it was waiting for aniview.hs.llnwd.net for at least three minutes.
Recieved email confirming account shortly after clicking button.
After 5 minutes, declared screw this, navigated to forum. This showed me as logged in.

Also, nothing is starred as required in account creation and that is sad.

**Comment by lostamongtrees** [comment]
This issue seems to be resolved. Thanks @DemiKara !
