### ISSUE TITLE
Header Font Inconsistency On INK Page

### ISSUE THREAD

**Issue by oleande-r** [RolePlayGateway/roleplaygateway#54]
Simply put, the original font for the header in the dark theme is a serif typeface but when on the INK page it becomes a different, sans serif typeface. Pictures below to illustrate the issue.

Original Header Font:
![](https://i.imgur.com/4DxjNAJ.png)

INK Page Header Font:
![](https://i.imgur.com/cxLcxr4.png)

**Comment by martindale** [comment]
I haven't had time to look at this yet, but it should be a simple fix in [this here file](https://github.com/RolePlayGateway/roleplaygateway/blob/master/styles/RolePlayGateway/template/ledger.html).  The CSS is included from @fractaloop inline, but needs to find a better home (after being tidied for integration).

**Comment by martindale** [comment]
This is now fixed!
