### ISSUE TITLE
Potential minor error in "custom.js" in regards to $('#'chatList').on

### ISSUE THREAD

**Issue by colearkenach** [RolePlayGateway/roleplaygateway#56]
https://image.prntscr.com/image/DhOcCDeJThGlPquxDZGjJA.png

As seen here, "$('#chatList').on('scroll', function() {" is missing a space between ".on" and ('scroll',...)

This was found using the inspector. The issue also apparently exists similarly in "VM821 custom.js", though it looks like this is a non-editable, debugger version of custom.js

I'm not sure if this affects anything major however.

**Comment by lostamongtrees** [comment]
@Jhar226 link leads to 403-has this been resolved?

**Comment by lostamongtrees** [comment]
Closing this issue as it seems relevant to oldchat
