### ISSUE TITLE
Character Creation Brings up Different Error

### ISSUE THREAD

**Issue by DemiKara** [RolePlayGateway/roleplaygateway#59]
Use Long_Lost_Luis reports having the following error code pop up. Reports that he did attempt to upload a 99x99 character image. This was for Black and White by The Great Thundorz.  Character name is Paarl, and has no nonstandard characters.
http://i.imgur.com/IsVhZgo.png

Player completely cleared cache, saved passwords, web history, cookies, etc and is still unable to submit.

**Comment by DemiKara** [comment]
Player has tried with and without images.

**Comment by martindale** [comment]
Image should be `100x100`, can you retry with correct dimensions?

**Comment by lostamongtrees** [comment]
see #83  - closing this issue, thank you again @DemiKara !
