### ISSUE TITLE
Live Notifications

### ISSUE THREAD

**Issue by monopoisoner** [RolePlayGateway/roleplaygateway#6]
Our current notifications system _technically_ works, but the count doesn't update and remains at a steady zero. One would need to manually click the zero to see if they have any new notifications. It would also be nice to include more forum-based features with them, such as new posts in subscribed threads or quotes/tags.

- [ ] bugfix current system
- [ ] include forum-based notifications

**Comment by lostamongtrees** [comment]
Resolved notification counter! Thank you @monopoisoner !
Going to open a new issue in regards to forum based notifications.
