### ISSUE TITLE
Editing a roleplay leads to error

### ISSUE THREAD

**Issue by izoi** [RolePlayGateway/roleplaygateway#63]
So.. like the title says, trying to edit a roleplay's information leads to an error.
As far as I'm aware it is one that could possibly be replicated.
What happened?
I decided to edit the description, introduction, and rules of one of my roleplays. Upon completion I clicked submit and it generated a MySQL error.
> General Error
SQL ERROR [ mysqli ]

Data too long for column 'description' at row 1 [1406]
![screen shot 2017-08-11 at 4 28 50 pm](https://user-images.githubusercontent.com/20009775/29232626-393422a6-7eb2-11e7-96ca-5bcb70fbc564.png)

Tried logging out and back in, refresh, editing one category at a time.

**Comment by martindale** [comment]
The description is too long, it has a maximum limit.  Probably something like `longtext`.  What're you trying to put in there?

**Comment by izoi** [comment]
I have two sentences in the description box below the title.
"What if I told you that all the stories you were told as a child were true? But, remember magic always comes with a price..."

Then the introduction is roughly three paragraphs with minimal BBCode. Editing any of it returned the error above and did not tell me the text was too long.

**Comment by lostamongtrees** [comment]
Seems to be resolved. Thank you! Closing -if anything changes let us know and thanks again @izoi !
