### ISSUE TITLE
Chat is blank when over 300+ items in cache

### ISSUE THREAD

**Issue by colearkenach** [RolePlayGateway/roleplaygateway#67]
Whenever my cache has over 300 items in it, chat is blank and I need to clear cache and reload chat. Example of how chat looks: http://prntscr.com/gj8vtb

**Comment by martindale** [comment]
What do you mean, 300 items?  Where are you getting this number from?

**Comment by colearkenach** [comment]
This came from my Google Chrome's cache list when I go to clear the history. I was mistaken in saying 300 _items_ because only the Browsing History counts things by items. 300 MB is what I meant to say. But, it looks like this problem isn't happening anymore and it might have been fixed when the site was reset after crashing once.  I'm not sure. 🤔 I'll keep an eye out though.

**Comment by martindale** [comment]
Marking as resolved.  Open a new issue if it happens again!
