### ISSUE TITLE
Etherpad: Backspace inserts a Return

### ISSUE THREAD

**Issue by BranTheBard** [RolePlayGateway/roleplaygateway#68]
After typing content, whenever backspace is used to erase characters, a return is inserted.
Sometimes, unreliably, the cursor moves to the new return and any attempt to backspace to the last row is met with another return and the cursor being dragged down.

The arrow keys or mouse and delete function can be used in place of backspace without issue.

**Comment by lostamongtrees** [comment]
Resolved-thank you @BranTheBard !
