### ISSUE TITLE
RP OOC Chat displays messages from MV OOC

### ISSUE THREAD

**Issue by BranTheBard** [RolePlayGateway/roleplaygateway#69]
If a message is sent to RP OOC chat, it pulls the most recent messages from the MV OOC chat and briefly flashes the MV OOC userlist on the right before loading the RP OOC userlist once more.

Lostamongtrees has confirmed that the messages are not being sent to the MV OOC when typed into RP OOC.

MartinVole claims they submitted this issue once before.

![rpchatissues-3](https://user-images.githubusercontent.com/31872536/30305846-1201e62e-9743-11e7-921f-14e8b06d723b.png)

I cleared my browsing data just to ensure it wasn't my browser. I use chrome.

![rpchatissues-2](https://user-images.githubusercontent.com/31872536/30305845-10201736-9743-11e7-92e6-7251c98d30e1.png)

Microsoft Edge: Same Result.
Mozilla Firefox: Same Result

**Comment by lostamongtrees** [comment]
Thank you @BranTheBard ! Closing this issue as we progress onward!
