### ISSUE TITLE
Characters marked as locations?

### ISSUE THREAD

**Issue by LookingatPerks** [RolePlayGateway/roleplaygateway#77]
Heyo, LookingAtPerks here!  So something I noticed but when you set a character to be sold in the marketplace the message shows up saying it's a location.  Could be small, could be big, but either way thought you would want to know.

**Comment by martindale** [comment]
This should now be fixed!  If you don't mind checking, you can close this issue when complete or comment if still broken.  Let us know either way!

**Comment by lostamongtrees** [comment]
This appears to be fixed -at all points of sell, the character is referenced as being a character and is listed as such in the marketplace
great work @LookingatPerks !
