### ISSUE TITLE
Official Chat

### ISSUE THREAD

**Issue by bumbahlee** [RolePlayGateway/roleplaygateway#79]
Rem had linked what he called 'an official chat' into chat on the site, but this comes up.

![2018-03-26](https://user-images.githubusercontent.com/28374618/37888100-15491d16-308b-11e8-918e-18bdfcf08daf.png)

I guess I put it here?

**Comment by martindale** [comment]
Where is the link in question?

**Comment by lostamongtrees** [comment]
> 
> 
> Where is the link in question?

they are going to chat.verse.pub
![image](https://user-images.githubusercontent.com/52435234/60755145-63953600-9fb9-11e9-9377-c59ec60addc9.png)

**Comment by martindale** [comment]
Everything should be pointing to chat.roleplaygateway.com, so if you spot a link to that URL add it to this thread.

**Comment by lostamongtrees** [comment]
Searched site-wide and cannot replicate error or find broken links,
Thank you @bumbahlee ! closing this issue
