### ISSUE TITLE
PM Links in Notifications

### ISSUE THREAD

**Issue by monopoisoner** [RolePlayGateway/roleplaygateway#8]
When attempting to access a new "Private Message" from the notifications page, it leads you to [this](http://i.imgur.com/UMlMg9n.png?1) error page. However, after accessing the message manually from your inbox, the link in the notifications page begins to work.

**Comment by lostamongtrees** [comment]
this seems to be fixed!
![image](https://user-images.githubusercontent.com/52435234/63245374-1352fa00-c22e-11e9-83a1-45872d173b3a.png)

leads to
![image](https://user-images.githubusercontent.com/52435234/63245402-24037000-c22e-11e9-89db-9213bd1c1202.png)
