### ISSUE TITLE
Millionaire Achievement 

### ISSUE THREAD

**Issue by bumbahlee** [RolePlayGateway/roleplaygateway#80]
So I passed the millionth word written on the site for maybe a few months now and for a bit I thought it was just the site being slow to issue the achievement, but then I talked to Cole and he said that Rem or Kuro had to issue it instead of it being automatically issued.

Photo proof down below? 
![2018-03-26 1](https://user-images.githubusercontent.com/28374618/37888190-934b198a-308b-11e8-8e2d-e4ad8278700e.png)
![2018-03-26 2](https://user-images.githubusercontent.com/28374618/37888192-935e6008-308b-11e8-8cef-77697d82a864.png)

**Comment by colearkenach** [comment]
More specifically I said it had to be issued manually because it looked like the millionaire achievement was only ever set to be issued once at the start. So other users could've been missed too.

**Comment by martindale** [comment]
Some achievements are not updated in real-time. See #28 for complete status.

**Comment by lostamongtrees** [comment]
Thanks bumbahlee and Jhar266! Closing this issue as we move forward
