### ISSUE TITLE
Questionable Character Market Transaction??

### ISSUE THREAD

**Issue by ErsatzCreedRPGW** [RolePlayGateway/roleplaygateway#82]
When i was buying something off the Market, it gave me the successful transaction thing but then I had to log back in because i guess i was signed out
I checked on the marketplace, the item (a character) says it was sold for 100 ink and that it is owneed by anonymous but i dunno if theres a guy named anonymous who purchased it when I had to sign back in OR if the marketplace literally threw the character into Limbo

I don't believe it charged me for the Ink if that helps. I don't care if someone else beat me to the char but itd suck if the character got thrown into limbo.

**Comment by martindale** [comment]
Whoa, nice find!  Thanks for taking the time to report this — you've been awarded [the "Bug Hunter" medal](https://www.roleplaygateway.com/medals/bug-hunter) as a result.  This has been fixed and the character has been moved to your inventory!

> `testnet` things.
