### ISSUE TITLE
Image size limitations not clear, poorly communicated on Error

### ISSUE THREAD

**Issue by colearkenach** [RolePlayGateway/roleplaygateway#83]
Attempting to choose a profile picture for the following character [Matria Flynn](https://www.roleplaygateway.com/roleplay/the-multiverse/characters/matria-flynn) returns the following error: https://prnt.sc/je5pzt

This persists whether attempting to upload a .jpg or .png - both of the files attempted were also 100x100 or smaller.

**Comment by colearkenach** [comment]
Image in question trying to be uploaded as the profile image.

![rsz_mirta_gev](https://user-images.githubusercontent.com/11782155/39667753-ee319314-508a-11e8-8d77-cf4ff25790df.png)

**Comment by martindale** [comment]
That image is 125 kB, which is pretty large — try reducing the number of colors or otherwise restricting the file size somehow.

**Comment by colearkenach** [comment]
Done and it works now. 😄 

An error displaying the image's file size being too large may help in the future (similar to the one in place if it's not 100x100 or smaller). But otherwise, this is all worked out. Thanks!

**Comment by lostamongtrees** [comment]
Thank you so much Jhar226! Closing this issue
