### ISSUE TITLE
Backspace Button Causes Cursor Mayhem

### ISSUE THREAD

**Issue by Lady-Awinita** [RolePlayGateway/roleplaygateway#84]
Scorpion01 and I came across this glitch some time ago and we have reported it many time,s but nobody took notice of it. so maybe now it will get noticed

Pressing BACKSPACE will create a NEW LINE at the bottom of the document, delete key will remove those lines, but it will still screw things up. As such becuase of this glitch, we havent used write.roleplaygateway.com and have used piratepad or etherpad directly

If and when this is fixed we might consider migrating back to RPG Write

**Comment by lostamongtrees** [comment]
> 
> 
> Scorpion01 and I came across this glitch some time ago and we have reported it many time,s but nobody took notice of it. so maybe now it will get noticed

![image](https://user-images.githubusercontent.com/52435234/60755064-896e0b00-9fb8-11e9-8b57-2853e0188a0f.png)


> Pressing BACKSPACE will create a NEW LINE at the bottom of the document

![image](https://user-images.githubusercontent.com/52435234/60755074-9f7bcb80-9fb8-11e9-9b3e-d79e300a1052.png)

![image](https://user-images.githubusercontent.com/52435234/60755083-ad315100-9fb8-11e9-9aac-470b800bdb5d.png)
 
seemingly fixed? can anyone confirm?

**Comment by lostamongtrees** [comment]
This issue has been fixed; thank you Lady-Awinita and Scorpion01!
