### ISSUE TITLE
Summon Staff Button doesn't work in the chat

### ISSUE THREAD

**Issue by ChaoticMarin** [RolePlayGateway/roleplaygateway#85]
[Screenshot of the offending code](https://i.imgur.com/inc6r0L.png)

The div chatListColumn, highlighted in blue to show where it is physically on the page, is covering up the Summon Staff button. The Summon Staff button cannot be clicked unless you click the veeeeeery right edge of it that isn't highlighted in the screenshot. It's unlikely everyone will be able to figure that out on their own, since all but like one pixel isn't clickable. They'll probably just click it, nothing will happen and they'll think it doesn't work or worse, assume it does work but they're being ignored.

This looks like it could be a simple fix. I was able to fix this locally by adding the CSS "z-index:1;" to the sessionControls div id. [Like so](https://i.imgur.com/Tc6RcZF.png)

**Comment by lostamongtrees** [comment]
Thank you Marin! Closing this issue as we move forward
