### ISSUE TITLE
Ghost Locations

### ISSUE THREAD

**Issue by thaumatology** [RolePlayGateway/roleplaygateway#93]
https://www.roleplaygateway.com/roleplay/the-multiverse/places/9a7436f18d9d35aed41132b5772f2d22

![](https://cdn.discordapp.com/attachments/346817906069471265/475917062179520512/unknown.png)

Can't teleport to them or access them, but they come up on...that list...

**Comment by martindale** [comment]
What is the output of `/location` in this case?

**Comment by thaumatology** [comment]
Game Master (GM) Location: 0 (Out Of Character (OOC))

**Comment by martindale** [comment]
Is this limited to a particular character (or group of characters)?  How can I replicate this for myself?  Might be a "characters with no location" bug.

**Comment by lostamongtrees** [comment]
it's `/build direction nothing` - creates  a void you can` /placeName Whatever`

**Comment by thaumatology** [comment]
resolved!
