### ISSUE TITLE
Can't submit a Universe/RP

### ISSUE THREAD

**Issue by Ahimlilgina** [RolePlayGateway/roleplaygateway#94]
I tired submitting this role play, and each time i hit submit this error screen would pop up. Even when I submitted it with no pictures it would still come up. The thumbnail i made sure was 100x100. I have tired countless times to submit this, waited a few days and tried again still same outcome.  I emailed the support email but haven't gotten a response, someone suggested I post the issue here so here i am. I hope this gets fixed soon, thank you!

![evidence](https://user-images.githubusercontent.com/42196224/43815539-23fc14bc-9a9e-11e8-9626-35b25f7813ba.png)
![evidence 2](https://user-images.githubusercontent.com/42196224/43815542-2b0cbebe-9a9e-11e8-934c-ade79781d844.png)
![evidence 3](https://user-images.githubusercontent.com/42196224/43815545-2f6a6d9e-9a9e-11e8-8b9d-a4d834e53607.png)

**Comment by martindale** [comment]
The image is too large (by filesize).  Try reducing the number of colors, or re-encoding in a different format?

**Comment by Ahimlilgina** [comment]
I tried to submit it will no pictures at all, and i still got the error.

**Comment by Ahimlilgina** [comment]
I tired submitting it without the thumbnail, and it worked!

**Comment by lostamongtrees** [comment]
Awesome; closing this issue, thank you Ahimlilgina!
