### ISSUE TITLE
Can't exit vehicle

### ISSUE THREAD

**Issue by thaumatology** [RolePlayGateway/roleplaygateway#96]
![image](https://user-images.githubusercontent.com/31420084/43991613-e96b2b0a-9d3e-11e8-87ee-098b69feab3c.png)

/exit doesn't work to exit vehicle , results in
Game Master (GM) says: You cannot exit something in which you are not.

**Comment by martindale** [comment]
Check `/vehicle` to make sure you're still "on board".  Try to figure out what causes you to exit the vehicle once "/board" is successfully run.

**Comment by lostamongtrees** [comment]
`/exit` now works to exit vehicle

**Comment by martindale** [comment]
Awesome.  Please feel free to open another issue if anything else breaks!

**Comment by lostamongtrees** [comment]
![image](https://user-images.githubusercontent.com/52435234/64841951-a46b8580-d5ce-11e9-8c10-548a799e93e1.png)

exit seems to be a wee bit broke again
- `/exit` did not work & made the entire room glitch out
- `/exit` kicked my character aaaaallll the way out

![image](https://user-images.githubusercontent.com/52435234/64842027-da106e80-d5ce-11e9-9264-f3ea79a35265.png)


maybe a minor issue, possibly related to #152 & #158
