### ISSUE TITLE
/ic not working in explore

### ISSUE THREAD

**Issue by thaumatology** [RolePlayGateway/roleplaygateway#97]
![image](https://user-images.githubusercontent.com/31420084/43991646-ad4bd4d4-9d3f-11e8-9d85-cd6bc22d3047.png)

Can't seem to switch  between characters in Explore using /ic command

**Comment by martindale** [comment]
The Explorer is _always_ IC — each character has its own dedicated chat now.

**Comment by thaumatology** [comment]
Ah I see! Hopefully “explore” click list will display all characters soon?
