### ISSUE TITLE
snippet redirect to seemingly irrelevant location

### ISSUE THREAD

**Issue by thaumatology** [RolePlayGateway/roleplaygateway#98]
![image](https://user-images.githubusercontent.com/31420084/43992420-1d8b045c-9d4c-11e8-9490-7985db0053c8.png)
 

"5 years ago" posted in the-multiverse/places/exalted-mountains, character Smaragdos, leads to location page for Impervious Door, specifically /the-multiverse/places/the-impervious-door?start=0#roleplay2376668

**Comment by lostamongtrees** [comment]
Tried the same snippet, this time it leads here
![image](https://user-images.githubusercontent.com/52435234/60764181-cd155300-a052-11e9-917e-83ebae35f0c7.png)

_result of deleting posts, thus **renumbering** overall?_

**Comment by lostamongtrees** [comment]
see #76 

> As the title says, every time you delete a post the content will in fact disappear, but a roleplay will still say "1 post here" even if nothing is there. If you go to the location that the post was posted in it will say the same, and it is wrong for character profiles as well. The post counter continues to be incorrect even when posting again or refreshing.
> Going to the location where the post was deleted from (link here) will say that there is "1 post here" even though there isn't anything there. All of the characters in the roleplay also have an additional post added to their "Seen x times" counter.
@oleande-r

**Comment by lostamongtrees** [comment]
see #71 
> The timestamp on a post (seemingly all posts) on this page:
> https://www.roleplaygateway.com/roleplay/the-multiverse/places/the-golden-vale
> 
> Lead to here :
> https://www.roleplaygateway.com/roleplay/the-multiverse/places/granpaix?start=75#roleplay2727781
> 
> Screenshot:
> https://i.imgur.com/KRA7213.jpg
> 
> (having trouble uploading images)

**Comment by lostamongtrees** [comment]
see #20 

> Specifically, I'm going through some of my character's old Multiverse posts, tagging all the things I remember, and notice that some of my old Gambit's Bar posts redirect to Castelia City. The post id number remains intact, so it's likely that you'll be taken to an empty activity page.
Why:
> No freaking clue. At first I thought that this was fixed to the location with the most recent post (and this bug was duplicated in another RP by Marin) but it's still going to Castelia even though the most recent post is currently in Lumiose City.

**Comment by lostamongtrees** [comment]
> 
> 
> see #71
> 
> > The timestamp on a post (seemingly all posts) on this page:
> > https://www.roleplaygateway.com/roleplay/the-multiverse/places/the-golden-vale
> > Lead to here :
> > https://www.roleplaygateway.com/roleplay/the-multiverse/places/granpaix?start=75#roleplay2727781
> > Screenshot:
> > https://i.imgur.com/KRA7213.jpg
> > (having trouble uploading images)

This seems to have been fixed!
Going to close this issue unless it is noticed again
